kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: offmesh-cni-node
  namespace: dapr-system
  labels:
    k8s-app: offmesh-cni-node
spec:
  selector:
    matchLabels:
      k8s-app: offmesh-cni-node
  template:
    metadata:
      labels:
        k8s-app: offmesh-cni-node
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: dapr-operator
      containers:
        - name: cni-node
          image: "{{ .Values.global.registry }}/offmesh-cni:{{ .Values.global.tag }}"
          command:
            - "/cni-node"
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            runAsNonRoot: false
            privileged: true
            capabilities:
              add: [ "NET_ADMIN" ]
          volumeMounts:
            - mountPath: /etc/offmesh
              name: offmesh-conf
            - mountPath: /host/root
              name: root
              readOnly: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
      volumes:
        - name: offmesh-conf
          configMap:
            name: offmesh-conf
        - hostPath:
            path: /
            name: root